// SPDX-License-Identifier: Apache-2.0 OR MIT
// ref: https://github.com/apollographql/apollo-rs 8b64f55db8843e6f90e087e6bc77a91b8c45a537
use crate::cst_src::KindsSrc;
use crate::reformat;
use anyhow::Result;
use proc_macro2::Punct;
use proc_macro2::Spacing;
use quote::format_ident;
use quote::quote;

pub(crate) fn generate_kinds(kinds: KindsSrc) -> Result<String> {
    let (single_byte_tokens_values, single_byte_tokens): (Vec<_>, Vec<_>) = kinds
        .punct
        .iter()
        .filter(|(token, _name)| token.len() == 1)
        .map(|(token, name)| (token.chars().next().unwrap(), format_ident!("{}", name)))
        .unzip();

    let punctuation_values = kinds.punct.iter().map(|(token, _name)| {
        if "{}[]()".contains(token) {
            let c = token.chars().next().unwrap();
            quote! { #c }
        } else {
            let cs = token.chars().map(|c| Punct::new(c, Spacing::Joint));
            quote! { #(#cs)* }
        }
    });
    let punctuation =
        kinds.punct.iter().map(|(_token, name)| format_ident!("{}", name)).collect::<Vec<_>>();

    let full_keywords_values = &kinds.keywords;
    let full_keywords = full_keywords_values.iter().map(|kw| format_ident!("{}_KW", kw));

    let all_keywords_values = kinds.keywords.iter().collect::<Vec<_>>();
    let all_keywords_idents = all_keywords_values.iter().map(|kw| format_ident!("{}", kw));
    let all_keywords =
        all_keywords_values.iter().map(|name| format_ident!("{}_KW", name)).collect::<Vec<_>>();

    let literals = kinds.literals.iter().map(|name| format_ident!("{}", name)).collect::<Vec<_>>();

    let tokens = kinds.tokens.iter().map(|name| format_ident!("{}", name)).collect::<Vec<_>>();

    let nodes = kinds.nodes.iter().map(|name| format_ident!("{}", name)).collect::<Vec<_>>();

    let cst = quote! {
        #![allow(bad_style, missing_docs, unreachable_pub, clippy::manual_non_exhaustive, clippy::upper_case_acronyms)]
        /// A token generated by the `Parser`.
        #[non_exhaustive]
        #[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
        #[repr(u16)]
        pub enum SyntaxKind {
            // Technical SyntaxKinds: they appear temporally during parsing,
            // but never end up in the final tree
            #[doc(hidden)]
            TOMBSTONE,
            #[doc(hidden)]
            EOF,
            #(#punctuation,)*
            #(#all_keywords,)*
            #(#literals,)*
            #(#tokens,)*
            #(#nodes,)*

            // Technical kind so that we can cast from u16 safely
            #[doc(hidden)]
            __LAST,
        }
        use self::SyntaxKind::*;

        impl SyntaxKind {
            pub fn is_keyword(self) -> bool {
                matches!(self, #(#all_keywords)|*)
            }

            pub fn is_punct(self) -> bool {
                matches!(self, #(#punctuation)|*)
            }

            pub fn is_literal(self) -> bool {
                matches!(self, #(#literals)|*)
            }

            pub fn from_keyword(ident: &str) -> Option<SyntaxKind> {
                let kw = match ident {
                    #(#full_keywords_values => #full_keywords,)*
                    _ => return None,
                };
                Some(kw)
            }

            pub fn from_char(c: char) -> Option<SyntaxKind> {
                let tok = match c {
                    #(#single_byte_tokens_values => #single_byte_tokens,)*
                    _ => return None,
                };
                Some(tok)
            }
        }

        /// Create a new `SyntaxKind`.
        #[macro_export]
        macro_rules! S_ {
            #([#punctuation_values] => { $crate::SyntaxKind::#punctuation };)*
            #([#all_keywords_idents] => { $crate::SyntaxKind::#all_keywords };)*
            [ident] => { $crate::SyntaxKind::IDENT };
            [int_number] => { $crate::SyntaxKind::INT_NUMBER };
            [float_number] => { $crate::SyntaxKind::FLOAT_NUMBER };
            [string] => { $crate::SyntaxKind::STRING };
        }

        impl ::core::marker::Copy for SyntaxKind {}
    };

    Ok(format_macro(reformat(&cst.to_string())?))
}

fn format_macro(result: String) -> String {
    if let Some(start) = result.find("macro_rules ! S_")
        && let Some(macro_end) = result[start..].find("\nimpl ::core::marker::Copy")
    {
        let macro_section = &result[start..start + macro_end];
        let formatted_macro = macro_section
            .replace("S_ { [", "S_ {\n    [")
            .replace(" ; [", ";\n    [")
            .replace(" ; }", ";\n}")
            .trim_end()
            .to_owned()
            + "\n";
        return result.replace(macro_section, &formatted_macro);
    }

    result
}
