//! This is a generated file, please do not edit manually. Changes can be
//! made in code generation that lives in `xtask` top-level dir.

#![allow(
    bad_style,
    missing_docs,
    unreachable_pub,
    clippy::manual_non_exhaustive,
    clippy::upper_case_acronyms
)]
#[doc = r" A token generated by the `Parser`."]
#[non_exhaustive]
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
#[repr(u16)]
pub enum SyntaxKind {
    #[doc(hidden)]
    TOMBSTONE,
    #[doc(hidden)]
    EOF,
    L_PAREN,
    R_PAREN,
    L_BRACK,
    R_BRACK,
    DOT,
    COMMA,
    EQ,
    PLUS_EQ,
    MINUS_EQ,
    STAR_EQ,
    SLASH_EQ,
    PERCENT_EQ,
    PLUS,
    MINUS,
    STAR,
    SLASH,
    BACK_SLASH,
    PERCENT,
    LT,
    GT,
    LTEQ,
    GTEQ,
    EQEQ,
    NEQ,
    AMP2,
    PIPE2,
    AMP,
    PIPE,
    SHL,
    SHR,
    BANG,
    As_KW,
    Auto_KW,
    AutoReadOnly_KW,
    Bool_KW,
    Else_KW,
    ElseIf_KW,
    EndEvent_KW,
    EndFunction_KW,
    EndIf_KW,
    EndProperty_KW,
    EndState_KW,
    EndWhile_KW,
    Event_KW,
    Extends_KW,
    False_KW,
    Float_KW,
    Function_KW,
    Global_KW,
    If_KW,
    Import_KW,
    Int_KW,
    Length_KW,
    Native_KW,
    New_KW,
    None_KW,
    Parent_KW,
    Property_KW,
    Return_KW,
    ScriptName_KW,
    Self_KW,
    State_KW,
    String_KW,
    True_KW,
    While_KW,
    INT_NUMBER,
    FLOAT_NUMBER,
    STRING,
    ERROR,
    IDENT,
    CUSTOM_FLAG,
    WHITESPACE,
    NEWLINE,
    COMMENT,
    SOURCE_FILE,
    SCRIPT,
    HEADER,
    SCRIPT_NAME_DECL,
    EXTENDS_CLAUSE,
    IMPORT,
    NAME,
    NAME_REF,
    TYPE,
    BASE_TYPE,
    PRIMITIVE_TYPE,
    CUSTOM_TYPE,
    ARRAY_SUFFIX,
    PARAM_LIST,
    PARAM,
    FLAG_MODIFIER,
    INLINE_PROPERTY,
    FULL_PROPERTY,
    PROPERTY_MEMBER,
    STATE,
    STATE_MEMBER,
    FUNCTION,
    RETURN_TYPE,
    EVENT,
    BLOCK,
    STMT,
    VAR_DECL_STMT,
    INITIALIZER,
    ASSIGN_STMT,
    RETURN_STMT,
    IF_STMT,
    ELSE_IF_BRANCH,
    ELSE_BRANCH,
    WHILE_STMT,
    EXPR_STMT,
    EXPR,
    PAREN_EXPR,
    BIN_EXPR,
    PREFIX_EXPR,
    CALL_EXPR,
    ARG_LIST,
    METHOD_CALL_EXPR,
    FIELD_EXPR,
    INDEX_EXPR,
    CAST_EXPR,
    NEW_EXPR,
    LITERAL,
    #[doc(hidden)]
    __LAST,
}
use self::SyntaxKind::*;
impl SyntaxKind {
    pub fn is_keyword(self) -> bool {
        matches!(
            self,
            As_KW
                | Auto_KW
                | AutoReadOnly_KW
                | Bool_KW
                | Else_KW
                | ElseIf_KW
                | EndEvent_KW
                | EndFunction_KW
                | EndIf_KW
                | EndProperty_KW
                | EndState_KW
                | EndWhile_KW
                | Event_KW
                | Extends_KW
                | False_KW
                | Float_KW
                | Function_KW
                | Global_KW
                | If_KW
                | Import_KW
                | Int_KW
                | Length_KW
                | Native_KW
                | New_KW
                | None_KW
                | Parent_KW
                | Property_KW
                | Return_KW
                | ScriptName_KW
                | Self_KW
                | State_KW
                | String_KW
                | True_KW
                | While_KW
        )
    }
    pub fn is_punct(self) -> bool {
        matches!(
            self,
            L_PAREN
                | R_PAREN
                | L_BRACK
                | R_BRACK
                | DOT
                | COMMA
                | EQ
                | PLUS_EQ
                | MINUS_EQ
                | STAR_EQ
                | SLASH_EQ
                | PERCENT_EQ
                | PLUS
                | MINUS
                | STAR
                | SLASH
                | BACK_SLASH
                | PERCENT
                | LT
                | GT
                | LTEQ
                | GTEQ
                | EQEQ
                | NEQ
                | AMP2
                | PIPE2
                | AMP
                | PIPE
                | SHL
                | SHR
                | BANG
        )
    }
    pub fn is_literal(self) -> bool { matches!(self, INT_NUMBER | FLOAT_NUMBER | STRING) }
    pub fn from_keyword(ident: &str) -> Option<SyntaxKind> {
        let kw = match ident {
            _ if ident.eq_ignore_ascii_case("As") => As_KW,
            _ if ident.eq_ignore_ascii_case("Auto") => Auto_KW,
            _ if ident.eq_ignore_ascii_case("AutoReadOnly") => AutoReadOnly_KW,
            _ if ident.eq_ignore_ascii_case("Bool") => Bool_KW,
            _ if ident.eq_ignore_ascii_case("Else") => Else_KW,
            _ if ident.eq_ignore_ascii_case("ElseIf") => ElseIf_KW,
            _ if ident.eq_ignore_ascii_case("EndEvent") => EndEvent_KW,
            _ if ident.eq_ignore_ascii_case("EndFunction") => EndFunction_KW,
            _ if ident.eq_ignore_ascii_case("EndIf") => EndIf_KW,
            _ if ident.eq_ignore_ascii_case("EndProperty") => EndProperty_KW,
            _ if ident.eq_ignore_ascii_case("EndState") => EndState_KW,
            _ if ident.eq_ignore_ascii_case("EndWhile") => EndWhile_KW,
            _ if ident.eq_ignore_ascii_case("Event") => Event_KW,
            _ if ident.eq_ignore_ascii_case("Extends") => Extends_KW,
            _ if ident.eq_ignore_ascii_case("False") => False_KW,
            _ if ident.eq_ignore_ascii_case("Float") => Float_KW,
            _ if ident.eq_ignore_ascii_case("Function") => Function_KW,
            _ if ident.eq_ignore_ascii_case("Global") => Global_KW,
            _ if ident.eq_ignore_ascii_case("If") => If_KW,
            _ if ident.eq_ignore_ascii_case("Import") => Import_KW,
            _ if ident.eq_ignore_ascii_case("Int") => Int_KW,
            _ if ident.eq_ignore_ascii_case("Length") => Length_KW,
            _ if ident.eq_ignore_ascii_case("Native") => Native_KW,
            _ if ident.eq_ignore_ascii_case("New") => New_KW,
            _ if ident.eq_ignore_ascii_case("None") => None_KW,
            _ if ident.eq_ignore_ascii_case("Parent") => Parent_KW,
            _ if ident.eq_ignore_ascii_case("Property") => Property_KW,
            _ if ident.eq_ignore_ascii_case("Return") => Return_KW,
            _ if ident.eq_ignore_ascii_case("ScriptName") => ScriptName_KW,
            _ if ident.eq_ignore_ascii_case("Self") => Self_KW,
            _ if ident.eq_ignore_ascii_case("State") => State_KW,
            _ if ident.eq_ignore_ascii_case("String") => String_KW,
            _ if ident.eq_ignore_ascii_case("True") => True_KW,
            _ if ident.eq_ignore_ascii_case("While") => While_KW,
            _ => return None,
        };
        Some(kw)
    }
    pub fn from_char(c: char) -> Option<SyntaxKind> {
        let tok = match c {
            '(' => L_PAREN,
            ')' => R_PAREN,
            '[' => L_BRACK,
            ']' => R_BRACK,
            '.' => DOT,
            ',' => COMMA,
            '=' => EQ,
            '+' => PLUS,
            '-' => MINUS,
            '*' => STAR,
            '/' => SLASH,
            '\\' => BACK_SLASH,
            '%' => PERCENT,
            '<' => LT,
            '>' => GT,
            '&' => AMP,
            '|' => PIPE,
            '!' => BANG,
            _ => return None,
        };
        Some(tok)
    }
}
#[doc = r" Create a new `SyntaxKind`."]
#[macro_export]
macro_rules ! S_ {
    ['('] => { $ crate :: SyntaxKind :: L_PAREN };
    [')'] => { $ crate :: SyntaxKind :: R_PAREN };
    ['['] => { $ crate :: SyntaxKind :: L_BRACK };
    [']'] => { $ crate :: SyntaxKind :: R_BRACK };
    [.] => { $ crate :: SyntaxKind :: DOT };
    [,] => { $ crate :: SyntaxKind :: COMMA };
    [=] => { $ crate :: SyntaxKind :: EQ };
    [+=] => { $ crate :: SyntaxKind :: PLUS_EQ };
    [-=] => { $ crate :: SyntaxKind :: MINUS_EQ };
    [*=] => { $ crate :: SyntaxKind :: STAR_EQ };
    [/=] => { $ crate :: SyntaxKind :: SLASH_EQ };
    [%=] => { $ crate :: SyntaxKind :: PERCENT_EQ };
    [+] => { $ crate :: SyntaxKind :: PLUS };
    [-] => { $ crate :: SyntaxKind :: MINUS };
    [*] => { $ crate :: SyntaxKind :: STAR };
    [/] => { $ crate :: SyntaxKind :: SLASH };
    ['\\'] => { $ crate :: SyntaxKind :: BACK_SLASH };
    [%] => { $ crate :: SyntaxKind :: PERCENT };
    [<] => { $ crate :: SyntaxKind :: LT };
    [>] => { $ crate :: SyntaxKind :: GT };
    [<=] => { $ crate :: SyntaxKind :: LTEQ };
    [>=] => { $ crate :: SyntaxKind :: GTEQ };
    [==] => { $ crate :: SyntaxKind :: EQEQ };
    [!=] => { $ crate :: SyntaxKind :: NEQ };
    [&&] => { $ crate :: SyntaxKind :: AMP2 };
    [||] => { $ crate :: SyntaxKind :: PIPE2 };
    [&] => { $ crate :: SyntaxKind :: AMP };
    [|] => { $ crate :: SyntaxKind :: PIPE };
    [<<] => { $ crate :: SyntaxKind :: SHL };
    [>>] => { $ crate :: SyntaxKind :: SHR };
    [!] => { $ crate :: SyntaxKind :: BANG };
    [As] => { $ crate :: SyntaxKind :: As_KW };
    [Auto] => { $ crate :: SyntaxKind :: Auto_KW };
    [AutoReadOnly] => { $ crate :: SyntaxKind :: AutoReadOnly_KW };
    [Bool] => { $ crate :: SyntaxKind :: Bool_KW };
    [Else] => { $ crate :: SyntaxKind :: Else_KW };
    [ElseIf] => { $ crate :: SyntaxKind :: ElseIf_KW };
    [EndEvent] => { $ crate :: SyntaxKind :: EndEvent_KW };
    [EndFunction] => { $ crate :: SyntaxKind :: EndFunction_KW };
    [EndIf] => { $ crate :: SyntaxKind :: EndIf_KW };
    [EndProperty] => { $ crate :: SyntaxKind :: EndProperty_KW };
    [EndState] => { $ crate :: SyntaxKind :: EndState_KW };
    [EndWhile] => { $ crate :: SyntaxKind :: EndWhile_KW };
    [Event] => { $ crate :: SyntaxKind :: Event_KW };
    [Extends] => { $ crate :: SyntaxKind :: Extends_KW };
    [False] => { $ crate :: SyntaxKind :: False_KW };
    [Float] => { $ crate :: SyntaxKind :: Float_KW };
    [Function] => { $ crate :: SyntaxKind :: Function_KW };
    [Global] => { $ crate :: SyntaxKind :: Global_KW };
    [If] => { $ crate :: SyntaxKind :: If_KW };
    [Import] => { $ crate :: SyntaxKind :: Import_KW };
    [Int] => { $ crate :: SyntaxKind :: Int_KW };
    [Length] => { $ crate :: SyntaxKind :: Length_KW };
    [Native] => { $ crate :: SyntaxKind :: Native_KW };
    [New] => { $ crate :: SyntaxKind :: New_KW };
    [None] => { $ crate :: SyntaxKind :: None_KW };
    [Parent] => { $ crate :: SyntaxKind :: Parent_KW };
    [Property] => { $ crate :: SyntaxKind :: Property_KW };
    [Return] => { $ crate :: SyntaxKind :: Return_KW };
    [ScriptName] => { $ crate :: SyntaxKind :: ScriptName_KW };
    [Self] => { $ crate :: SyntaxKind :: Self_KW };
    [State] => { $ crate :: SyntaxKind :: State_KW };
    [String] => { $ crate :: SyntaxKind :: String_KW };
    [True] => { $ crate :: SyntaxKind :: True_KW };
    [While] => { $ crate :: SyntaxKind :: While_KW };
    [ident] => { $ crate :: SyntaxKind :: IDENT };
    [int_number] => { $ crate :: SyntaxKind :: INT_NUMBER };
    [float_number] => { $ crate :: SyntaxKind :: FLOAT_NUMBER };
    [string] => { $ crate :: SyntaxKind :: STRING };
}

impl ::core::marker::Copy for SyntaxKind {}
